 [[language]]
 name = "python"
 scope = "source.python"
 injection-regex = "python"
 file-types = ["py"]
 shebangs = ["python"]
 roots = ["pyproject.toml", "setup.py", "Poetry.lock"]
 comment-token = "#"
 language-server = { command = "pyright-langserver", args = ["--stdio"] }
 auto-format = false
 indent = { tab-width = 4, unit = "    " }
 config = {}
