theme = "gruvbox"

[editor]
line-number = "relative"
mouse = false
bufferline = "multiple"

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.statusline]
left = ["mode", "spinner"]
center = ["file-name"]
right = ["diagnostics", "selections", "position", "file-encoding", "file-line-ending", "file-type"]
separator = "│"

[editor.whitespace.render]
space = "all"
tab = "all"
newline = "all"

[editor.whitespace.characters]
space = "·"
nbsp = "⍽"
tab = "→"
newline = "⏎"
tabpad = "·"

[keys.normal]
# Quick iteration on config changes
C-o = ":config-open"
C-r = ":config-reload"
esc = ["collapse_selection", "keep_primary_selection"]

# Personal preference
o = ["open_below", "normal_mode"]
O = ["open_above", "normal_mode"]
