theme = "rose_pine"

[editor]
line-number = "relative"
mouse = false
bufferline = "multiple"
color-modes = true

[editor.lsp]
display-messages = true

[editor.search]
smart-case = true

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.statusline]
left = [
  "mode",
  "spacer",
  "separator",
  "spacer",
  "spinner",
  "position-percentage",
  "spacer",
  "total-line-numbers",
  "spacer",
  "version-control"
]
center = ["file-name", "spacer", "diagnostics"]
right = ["selections", "position", "file-type", "spacer"]
separator = "│"

[editor.file-picker]
hidden = false

[editor.whitespace.render]
space = "all"
tab = "all"
newline = "all"

[editor.whitespace.characters]
space = "·"
nbsp = "⍽"
tab = "→"
newline = "⏎"
tabpad = "·"

[editor.indent-guides]
render = true
character = "▏" # Some characters that work well: "▏", "┆", "┊", "⸽"
skip-levels = 1

[keys.normal]
# Quick iteration on config changes
C-o = ":config-open"
C-r = ":config-reload"
C-q = ":buffer-close"

x = ["extend_line_below", "select_mode"]
X = ["extend_line_up", "extend_to_line_bounds", "select_mode"]

p = "paste_clipboard_after"
P = "paste_clipboard_before"

y = [
  "yank_main_selection_to_clipboard",
  "normal_mode",
  "flip_selections",
  "collapse_selection"
]
Y = [
  "extend_to_line_bounds",
  "yank_main_selection_to_clipboard",
  "goto_line_start",
  "collapse_selection"
]

esc = ["collapse_selection", "keep_primary_selection"]

H = [":buffer-previous"]
L = [":buffer-next"]

C-j = ["extend_to_line_bounds", "delete_selection", "paste_after"]
C-k = ["extend_to_line_bounds", "delete_selection", "move_line_up", "paste_before"]

C-a = "no_op"

[keys.select]
x = ["extend_line_below", "select_mode"]
X = ["extend_line_up", "extend_to_line_bounds"]

k = ["extend_line_up", "extend_to_line_bounds"]
j = ["extend_line_down", "extend_to_line_bounds"]

d = ["yank_main_selection_to_clipboard", "delete_selection"]

y = [
  "yank_main_selection_to_clipboard",
  "normal_mode",
  "flip_selections",
  "collapse_selection"
]
Y = [
  "extend_to_line_bounds",
  "yank_main_selection_to_clipboard",
  "goto_line_start",
  "collapse_selection",
  "normal_mode",
]

p = ":clipboard-paste-replace"
P = ":clipboard-paste-after"

esc = ["collapse_selection", "keep_primary_selection", "normal_mode"]
